### ISSUE TITLE
"rotd" option in input string not pressent in instrument files.

### ISSUE THREAD

**Issue by MartinAOlsen** [mads-bertelsen/guide_bot#7]
Using the rotd option to set a specific curvature on a curved guide section has no effect on the instrument files. The instrument files uses a LoS calculation to determine curvature instead. 

Bug encountered using this input string:
input{1}='S(start=1.9,StartHeight=0.055,StartWidth=0.07) C(rotd=v,start=2,rots=1,StartHeight=0.055,StartWidth=0.07,rotd=0.71602) C(rotd=v,start=22,rots=-1,rotd=0.71602,StartHeight=0.055,StartWidth=0.07) E(start=42,EndHeight=0.111,EndWidth=0.1) S(start=54.92,EndHeight=0.111,EndWidth=0.1) E(start=92.489,EndHeight=0.06215,EndWidth=0.075) S(start=105.666,EndHeight=0.06215,EndWidth=0.075) E(start=113.507,EndHeight=0.06215,EndWidth=0.062935) E(start=137.516,length=20.989,EndHeight=0.03729,EndWidth=0.0192) S(EndWidth=0.023,EndHeight=0.03729)';

**Comment by mads-bertelsen** [comment]
The option for forcing a certain angle deviation for the C and K module is rot, not rotd. I checked the input string with the update and get a correctly forced curvature.
rotd instead selects wether the rotation should be in the horizontal or vertical plane, as you also use in the input string. rots is the direction, and rot is the angle.

Sorry for the late answer!
